### PR TITLE
Update README - minor typos, add link to MP wiki

### PR DESCRIPTION
**Pull request by dwinston**
Nice job, @shyuep. I'll work on ensuring the top-level keys have READMEs

### CODE REVIEW

**Comment by shyuep** [comment]
Thanks. BTW, there is no need to send me pull requests. I trust you to do a great job at this. There isn't any code to review in any case!

**Comment by computron** [comment]
Technically, there could be a unit test that pulls down a full doc and
compares the keys with the folders. Then this is guaranteed to never fall
out of sync unintentionally

Best,
Anubhav

**Comment by shyuep** [comment]
That is true. But that would require the REST interface to support pulling down a full doc. :-) Fairly trivial to just move the materials/mp-1234/json into the REST layer. But I guess really the point is that this is mostly doc. So I am pretty flexible about people contributing to this and not having to review every single change. (Unlike code where bad commits can wreak havoc).

**Comment by dwinston** [comment]
OK well then @shyuep you should add me as a contributor to the repo so I have push access. :) Or add this repo to https://github.com/orgs/materialsproject/teams/materials-django-admin/repositories so I have push access through my "team" membership.

**Comment by shyuep** [comment]
Done. Strange, I actually added the MP Extended Team and Collaborators to the editors. I thought you were in those teams. Anyway, just added materials_django_admin. Like I said, this is one repo where the more people have edit access to it, the better. :-)

**Comment by shyuep** [comment]
BTW, I think the really critical ones to document are those where it is unclear what the differences in keys are. And this is something @computron and @tschaume may need to help you with. For example, I have no idea what snlgroup_\* means. There are a bunch of those with final, changed, etc. Also things like bandgap where there are like 4 different kinds of gaps.

**Pull request merged**
